export const LAZY_IMAGE_MODE_LOAD_DIRECTLY = 'LAZY_IMAGE_MODE_LOAD_DIRECTLY',
    LAZY_IMAGE_MODE_LOAD_WHEN_VISIBLE = 'LAZY_IMAGE_MODE_LOAD_WHEN_VISIBLE'

export const ARTICLE_COLORS = ['rgba(239, 223, 187, 0.3)', 'rgba(200, 230, 240, 0.3)', 'rgba(220, 237, 200, 0.3)', 'rgba(235, 220, 240, 0.3)', 'var(--fourth-background-color)']

export const EVENT_LOAD_LAZY_IMAGE = 'EVENT_LOAD_LAZY_IMAGE'

export const ERROR_NO_INTERNET_CONNECTION = 'ERROR_NO_INTERNET_CONNECTION',
    ONLINE_BACK = 'ONLINE_BACK',
    EVENT_CLEAR_PROTECTED_CACHE = 'EVENT_CLEAR_PROTECTED_CACHE'
